name: neural-network
version: 0.1.0.0
license: NONE
author: "olegalexander@gmail.com"
maintainer: "Oleg Alexander"

language: GHC2021


ghc-options:
  - -Wall
  - -O2
  - -Wno-unrecognised-pragmas


default-extensions: Strict


dependencies:
  - base >= 4.18.2.1
  - random >= 1.2.1.2
  - h-raylib >= 5.1.3.0
  - pretty-simple >= 4.1.2.0
  - vector >= 0.13.1.0
  - containers
  - cereal
  - bytestring
  - directory
  - filepath


library:
  source-dirs: src
  exposed-modules: NeuralNetwork


tests:
  test-suite-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - neural-network